### ISSUE TITLE
APIError: Invalid request made

### ISSUE THREAD

**Issue by Bolimha1234** [TheDrone7/disco-oauth#22]
I'm getting 400 status code, how to fix?

```js
app.get('/login', async (req, res) => {
  let code = req.query.code;
  if(code === undefined)
    res.send("Undefined")
  else {
   let userkey = await oauthClient.getAccess(code).catch(console.error);
    res.cookies.set("key", userkey)
    res.redirect(`/user`)
  }
})


app.get("/user/", async (req, res) => {
  let key = req.cookies.get("key")
  if(!key) return res.send("Error Happened!")
  if(key){
    let user = await oauthClient.getUser(key);
      console.log(user)
  }
  res.redirect("https://discord.com/channels/@me")
})

**Comment by sasial-dev** [comment]
Yeah, same here. :/

**Comment by TheDrone7** [comment]
Do you get it in the `/login` or `/user`?

**Comment by sqwyer** [comment]
Same thing happening with me, in response to TheDrone7, the error I get is in the `let userkey = await oauthClient.getAccess(code).catch(console.error);` ( getAccess method )

**Comment by TheDrone7** [comment]
The only possible issue here can be a network issue. The auth code expires really quickly and needs to be sent pretty much immediately. Just verified, cannot seem to reproduce.
