### ISSUE TITLE
Error: i.toLowerCase is not a function

### ISSUE THREAD

**Issue by brezedc** [TheDrone7/disco-oauth#28]
if (scopesList.includes(i.toLowerCase().trim())) {
                                  ^

TypeError: i.toLowerCase is not a function

I'm getting this issue when im starting my webserver. I have the latest node.js and disco-oauth.

Ive tried googling and looking up in the docs, but i can't find anything about it.

**Comment by TheDrone7** [comment]
Refer to old issues.
