### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by arthur-rl** [TheDrone7/disco-oauth#4]
Hi there, 
Every couple of minutes. Like when i work on the code for a couple of minutes and go back on the site and refresh the page i get a connection error. I was wondering how i deal with this to stop it happening. feel free to dm me on discord. arthurl#0001 and if that doesn't work because my nitro ran out join this  https://discord.gg/THr24Bb

**Comment by TheDrone7** [comment]
This has been fixed in the undocumented version `4.0.0` of the library, please update to fix the issue.
