### ISSUE TITLE
Not just my server setup

### ISSUE THREAD

**Issue by TheGoldenCactus11** [TheDrone7/disco-oauth#9]
![image](https://user-images.githubusercontent.com/41830820/71748853-bcac2c80-2e6b-11ea-8043-ed244ef6ce6e.png)

**Comment by TheDrone7** [comment]
It might be a connection issue, your browser's extensions might be interfering and not letting it make the appropriate requests. I gave it a try 2 minutes before posting this and everything works perfectly for me.

**Comment by TheDrone7** [comment]
I'd recommend following the format I provided for issue creating and also share the browser you're using and the OS along with any ad blockers if you have enabled some.
